name: Executable

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - .github/workflows/py_binding.yml
      - src/Python/**
      - pyproject.toml

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        arch: [ x86-64, x86-64-v2, x86-64-v3, x86-64-v4, apple-m1, apple-m2, apple-m3, apple-m4 ]
        os: [ ubuntu-latest , windows-latest, macos-latest ]
        include:
          - os: windows-latest
            extension: .exe
        exclude:
          - os: windows-latest
            arch: apple-m1
          - os: windows-latest
            arch: apple-m2
          - os: windows-latest
            arch: apple-m3
          - os: windows-latest
            arch: apple-m4
          - os: ubuntu-latest
            arch: apple-m1
          - os: ubuntu-latest
            arch: apple-m2
          - os: ubuntu-latest
            arch: apple-m3
          - os: ubuntu-latest
            arch: apple-m4
          - os: macos-latest
            arch: x86-64
          - os: macos-latest
            arch: x86-64-v2
          - os: macos-latest
            arch: x86-64-v3
          - os: macos-latest
            arch: x86-64-v4

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - if: matrix.os == 'ubuntu-latest'
      name: Install Linux Dependencies
      run: |
        sudo apt install ninja-build
        sudo apt remove python3-lldb-14
    - if: matrix.os == 'windows-latest'
      name: Install Windows Dependencies
      run: |
        choco install ninja

    - if: matrix.os == 'ubuntu-latest'
      name: Install Clang 20 (Ubuntu)
      run: |
        wget https://apt.llvm.org/llvm.sh
        sudo chmod +x llvm.sh
        sudo ./llvm.sh 20
        sudo rm -rf llvm.sh
    - if: matrix.os == 'windows-latest'
      name: Install Clang 20 (Windows)
      run: |
        choco install llvm --version 20.1.7 -y
    - if: matrix.os == 'macos-latest'
      name: Install Clang 20 (MacOS)
      run: |
        brew update-reset
        brew update
        brew install llvm@20

    - if: matrix.os == 'ubuntu-latest'
      name: Set CC and CXX for Linux
      run: |
        echo "CC=clang-20" >> $GITHUB_ENV
        echo "CXX=clang++-20" >> $GITHUB_ENV
    - if: matrix.os == 'windows-latest'
      name: Set CC and CXX for Windows
      shell: powershell
      run: |
        echo "CC=clang" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        echo "CXX=clang++" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
    - if: matrix.os == 'macos-latest'
      name: Set CC and CXX for MacOS
      run: |
        echo "CC=/opt/homebrew/opt/llvm@20/bin/clang" >> $GITHUB_ENV
        echo "CXX=/opt/homebrew/opt/llvm@20/bin/clang++" >> $GITHUB_ENV
        echo "PATH=/opt/homebrew/opt/llvm@20/bin:$PATH" >> $GITHUB_ENV

    - name: Configure CMake
      run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DCI=ON -DARCHITECTURE=${{ matrix.arch }} -G Ninja

    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}

    - if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
      name: Extract Version Identifier (Linux and MacOS)
      run: |
        VERSION=$(grep 'const std::string VERSION' ${{ github.workspace }}/build/Information.h | cut -d'"' -f2)
        echo "VERSION=${VERSION}" >> $GITHUB_ENV

    - if: matrix.os == 'windows-latest'
      name: Extract Version Identifier (Windows)
      shell: powershell
      run: |
        $VERSION = (Get-Content -Path ${{ github.workspace }}/build/BuildSystem/Information.h | Select-String -Pattern 'const std::string VERSION' -SimpleMatch).ToString().Split('"')[1]
        echo "VERSION=${VERSION}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Rename Binary
      run: |
        mv ${{ github.workspace }}/build/StockDory${{ matrix.extension }} ${{ github.workspace }}/StockDory-${{ env.VERSION }}-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.extension }}

    - name: Upload Binary
      uses: actions/upload-artifact@v4
      with:
        name: StockDory-${{ env.VERSION }}-${{ matrix.os }}-${{ matrix.arch }}
        path: ${{ github.workspace }}/StockDory-${{ env.VERSION }}-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.extension }}

