name: Linux Clang 20

on:
  push:
    branches: [ "0.1-comparison" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ninja-build
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 20

      - name: Build through Verdict entrypoint
        run: PATH=/usr/lib/llvm-20/bin:$PATH make openbench
